[package]
name = "example"
version = "0.1.0"
authors = ["Natanael Mojica <neithanmo@gmail.com>"]
edition = "2018"

[dependencies]
fluentbit = {path="../", version="0.1.0"}
libc = "0.2"
lazy_static = "1.3.0"

[lib]
crate-type=["cdylib"]
